version: "3"

services:
  digitaltwin-spawner:
    image: threefoldjimber/digitaltwin-spawner:${digitaltwin_spawner_tag}
    container_name: digitaltwin-spawner
    build: server
    restart: always
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/digitaltwin:/config
    networks:
      - chatnet
    environment:
      - DIGITALTWIN_APPID=${DIGITALTWIN_APPID}
      - ENVIRONMENT=${ENVIRONMENT}

  digitaltwin-proxy:
    image: threefoldjimber/digitaltwin-proxy:${digitaltwin_proxy_tag}
    container_name: digitaltwin-proxy
    restart: always
    build: proxy
    volumes:
      - ../certs:/etc/nginx/certs
    ports:
       - 443:443
       - 80:80
    networks:
       - chatnet

  digitaltwin-frontend:
    image: threefoldjimber/digitaltwin-frontend:${digitaltwin_frontend_tag}
    container_name: digitaltwin-frontend
    restart: always
    build: frontend
    networks:
      - chatnet
    environment:
      - DIGITALTWIN_APPID=${DIGITALTWIN_APPID}
      - ENVIRONMENT=${ENVIRONMENT}

  onlyoffice-documentserver:
    image: onlyoffice/documentserver
    container_name: onlyoffice-documentserver
    restart: always
    networks:
      - chatnet

networks:
  chatnet:
    external: true
