version: "3"

services:
  digitaltwin-spawner:
    container_name: digitaltwin-spawner
    build: server
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/digitaltwin:/config
    networks:
      - chatnet

  digitaltwin-proxy:
    image: nginx
    container_name: digitaltwin-proxy
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
    ports:
      - 443:443
      - 80:80
    networks:
      - chatnet

  digitaltwin-frontend:
    container_name: digitaltwin-frontend
    restart: always
    build: frontend
    networks:
      - chatnet

networks:
  chatnet:
    external: true
